# Generated by Django 4.2.4 on 2024-03-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=128)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True)),
            ],
        ),
    ]
